//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\oleg\projects\Dx12Setup\ReflectionGenerator\ShadersReflectionToCode\SRCPP\Generator\BindingsGrammar.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="BindingsGrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IBindingsGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitText([NotNull] BindingsGrammarParser.TextContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] BindingsGrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.binding"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinding([NotNull] BindingsGrammarParser.BindingContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.srvId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSrvId([NotNull] BindingsGrammarParser.SrvIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.texId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTexId([NotNull] BindingsGrammarParser.TexIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.uavId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUavId([NotNull] BindingsGrammarParser.UavIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.enum"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnum([NotNull] BindingsGrammarParser.EnumContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.enumElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumElements([NotNull] BindingsGrammarParser.EnumElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.enumElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumElement([NotNull] BindingsGrammarParser.EnumElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.enumValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumValue([NotNull] BindingsGrammarParser.EnumValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.struct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct([NotNull] BindingsGrammarParser.StructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFields([NotNull] BindingsGrammarParser.FieldsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField([NotNull] BindingsGrammarParser.FieldContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="BindingsGrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] BindingsGrammarParser.TypeContext context);
}
